version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: docker/nestjs/Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "npx prisma generate &&
             npx prisma studio &
             npm run start:dev"

    volumes:
      - .:/app  # Mount the src directory for live updates

  keycloak:
    build:
      context: .
      dockerfile: docker/keycloak/Dockerfile
    command: start-dev
    container_name: keycloak 
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - postgreskeycloak
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://postgreskeycloak:5433/keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak


  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgresprisma:/var/lib/postgresql/data


  postgreskeycloak:
    image: postgres:13
    container_name: postgreskeycloak
    restart: on-failure
    ports:
      - 5433:5433
    command: ["postgres", "-p", "5433"]     # This command override internal postgres port
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgreskeycloak:/var/lib/postgresql/data

volumes:
  postgresprisma:
    name: nest-prisma-docker-db
  postgreskeycloak:
    name: keycloak-docker-db